# Testing
ASCRIPT	= ./Aruntests
CSCRIPT	= ./Cruntests
OUT     = ./out/*

.PHONY: test clean clobber
# test the program
Atest:
	$(ASCRIPT)

Ctest:
	$(CSCRIPT)

# remove output files
clobber: clean

clean:
	rm -f $(OUT)
